### ISSUE TITLE
get the gene activity matrix  from ArchR

### ISSUE THREAD

**Issue by liyang24** [CostaLab/scMEGA#11]
hi!
I would like to know how to get the gene activity matrix in the example from ArchR, since I used the function `gene activity matrix`
to get a different object like this:
> gene.activity
class: SummarizedExperiment
dim: 14103 6791
metadata(0):
assays(1): GeneScoreMatrix
rownames: NULL
rowData names(6): seqnames start ... name idx
colnames(6791): #AAACGAAAGGATCCTT-1
  #AAACGAAAGGCATGCA-1 ... #TTTGTGTTCGATCGCG-1
  #TTTGTGTTCGATCTTT-1
colData names(15): DoubletEnrichment DoubletScore ... Clusters Celltype

**Comment by lzj1769** [comment]
Hi,

You can extract the gene activity matrix like this:

```
proj <- addGeneScoreMatrix(proj,
                           force = TRUE)
atac <- getMatrixFromProject(ArchRProj = proj,
                             useMatrix = "GeneScoreMatrix")
gene_counts <- atac@assays@data$GeneScoreMatrix
rownames(gene_counts) <- atac@elementMetadata$name
saveRDS(gene_counts, file = "../data/snATAC/GeneScoreMatrix.Rds")
```

**Comment by liyang24** [comment]
Thanks a lot ! i got it
