### ISSUE TITLE
snATAC data does not have a $Harmony dimension reduced matrix

### ISSUE THREAD

**Issue by liyang24** [CostaLab/scMEGA#13]
Hi! 
I noticed that I needed to use $Harmony in the tutorial to prepare the data

>#add dimension reduced matrix
harmony_matDR <- proj@reducedDims$Harmony$matDR

but I only had $UMAP in my data ,because my samples are not duplicated. 
In this case, can I still use this tutorial? How can I get the final obj.atac?

**Comment by lzj1769** [comment]
Sure, you can use the UMAP embedding.
