### ISSUE TITLE
Big data takes too long for cells to pair

### ISSUE THREAD

**Issue by liyang24** [CostaLab/scMEGA#16]
hi! Thanks for  this great work!
Since this is the data of merge in three periods, and I was using so many cells, this step took so long to get nowhere

> df.pair <- PairCells(object = coembed.sub, reduction = "harmony",pair.by = "tech", ident1 = "ATAC", ident2 = "RNA")
Getting dimensional reduction data for pairing cells...
Pairing cells using geodesic mode...
Constructing KNN graph for computing geodesic distance ..
Computing graph-based geodesic distance ..
KNN subgraphs detected: 1
Skipping subgraphs with either ATAC/RNA cells fewer than: 50
Pairing cells for subgraph No.1
Total ATAC cells in subgraph: 26748
Total RNA cells in subgraph: 29030
Subgraph size: 26748
Search threshold being used: 10700
Constructing KNN based on geodesic distance to reduce search pairing search space
Number of cells being paired: 26748 ATAC and 26748  RNA cells
Determing pairs through optimized bipartite matching ..

I would like to know whether I can get the obj.pair of each period first and then merge them together

**Comment by lzj1769** [comment]
Hi @liyang24 

Sure, you can run the PairCells function for each period individually, and then merge the paired cells afterward.

**Comment by liyang24** [comment]
Thanks! 
I got the merge obj now
