### ISSUE TITLE
 Use obj.pair to show the expression of marker gene

### ISSUE THREAD

**Issue by liyang24** [CostaLab/scMEGA#19]
Hi!
I use obj.pair to look at the expression of marker gene.
I want to know whether the gene expression matrix in scRNA or the gene score matrix in scATAC is used here ,or the expression quantity after algorithm integration?

> obj.pair
An object of class Seurat
67334 features across 5396 samples within 2 assays
Active assay: RNA (17352 features, 0 variable features)
 1 other assay present: ATAC
 4 dimensional reductions calculated: pca, umap, harmony, umap_harmony

> p <- FeaturePlot(obj.pair, features = c("COL1A1"),reduction ="umap_harmony",min.cutoff = "q10", max.cutoff = "q90")

**Comment by lzj1769** [comment]
Hi @liyang24 

Here, the gene expression matrix is used.

More specifically, in this object, each cell has two modalities, i.e., RNA and ATAC, generated from the two assays by integration.

So when you visualize the marker genes, the RNA data is used.
