### ISSUE TITLE
script for preparing data

### ISSUE THREAD

**Issue by htong3031** [CostaLab/scMEGA#20]
Dear author, 

I have noted that the script of cleaning the data and preparing neccessary objects is found in https://costalab.ukaachen.de/open_data/scMEGA/Fibroblast/01_prepare_data.html. However, I failed to identify the project and required folder ("../../../VisiumHeartRevision/IntegrativeAnalysis/Fibroblast/data/snATAC") in the tutorial. Where should I find that? 

Thank you.

**Comment by lzj1769** [comment]
Hi @htong3031 

With this example script, we want to show how to prepare the data from an ArchR project. Currently, we have not made this data avaialble, as the size is quite large.
