### ISSUE TITLE
The use of Co-embedding function

### ISSUE THREAD

**Issue by LalicJ** [CostaLab/scMEGA#22]
Hi, sorry to bother you. When I run Co-embedding(), I have a question.  If I don't ran harmony or other methods on snRNA-seq and snATAC-seq datasets for removing batch effect, what `weight.reduction` value should I use?

Do you have any suggestions?  Any help would be greatly appreciated.

**Comment by lzj1769** [comment]
Hi,

You can set weight.reduction as the dimension name used in snATAC-seq, such as LSI,
because here we aim to first transfer the gene expression profile from snRNA-seq to snATAC-seq.

Best,
Zhijian

**Comment by LalicJ** [comment]
Thanks! I'll try it.
