### ISSUE TITLE
AddTargetAssay

### ISSUE THREAD

**Issue by GischD** [CostaLab/scMEGA#26]
Hi

I am trying to run
```pbmc.t.cells <- AddTargetAssay(object = pbmc.t.cells, df.grn = df.grn2)```

Instead of me receiving the warning like in the vignettes

``` Warning in if (is.na(df.grn)) {: the condition has length > 1 and only the first element will be used```

The program is returning:

```Error in if (is.na(df.grn)) { : the condition has length > 1```

Do you have any idea what is going on?

Thank you,
Debora

**Comment by lzj1769** [comment]
Hi,

This could be related to the new version of Seurat.

I am working on this to make sure all functions are compatible with Seurat v5.

**Comment by GischD** [comment]
Hi 

For now I open the code and run the functions and works.

Thank you,
Debora
