### ISSUE TITLE
ArchR input

### ISSUE THREAD

**Issue by juanjaureguilozano** [CostaLab/scMEGA#5]
Hi! Congratulations on the paper and the package, it looks like it's going to be very useful.

I would like to run scMEGA with my 10X multiome data, and we normally do the RNA analysis with Seurat, and ATAC with ArchR. Your tutorial has a Seurat object for ATAC (probably generated with Signac). Could you please add specific information on how to generate the Seurat object from an ArchR project, rather than Signac? We prefer ArchR for ATAC analysis and I can't find an ArchR function to generate a Seurat object with ATAC peaks/counts.

Thank you so much!

**Comment by juanjaureguilozano** [comment]
Nevermind, I just found the script for preparing the data. https://costalab.ukaachen.de/open_data/scMEGA/Fibroblast/01_prepare_data.html

**Comment by lzj1769** [comment]
Hi @juanjaureguilozano,

Thanks for your interest. 
In this data preparation script, you can find how we convert the data from ArchR to the Seurat object.

Maybe later I will include this in our vignette so people can easily find it.

Best,
Zhijian
