### ISSUE TITLE
GRNSpatialPlot 

### ISSUE THREAD

**Issue by DLGisch** [CostaLab/scMEGA#8]
Hello scMEGA team,

Thank you for developed this tool.
I am trying to plot my samples with GRNSpatialPlot, but the images are coming stretched and deformed. The same happens on Seurat command SpatialFeaturePlot, but I just add crop=F and fixed.
For the GRNSpatialPlot I didn't find a similar option.

Best,
Debora

**Comment by lzj1769** [comment]
Hi @DLGisch ,

I have added crop option to GRNSpatialPlot function, can you re-install the package and try it again?

Thanks and best,
Zhijian

**Comment by DLGisch** [comment]
Hi Zhijian,

I re-install and all works well. 👍 

Thank you,
Debora
